### ISSUE TITLE
DotNetLive.Framework Nuget打包发布

### ISSUE THREAD

**Issue by dukecheng** [dotnetlive/dotnetlive#13]
**最终DotNetLive.Framework各个项目的nuget更新有几点要注意**
1. 必须是自动打包发布, 所以肯定要放到Jenkins上去做编译发布, 不会是人手工打包发布,.
2. 既然我们的核心是Cross Platform, 所以整个过程必须是在Linux(特指非Windows平台)上完成

**Comment by dukecheng** [comment]
参考文档: 
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-pack
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-nuget-push

**Comment by cdllqos** [comment]
@DukeCheng 打包命令:`dotnet pack -o ./` -o [打包输出路径]
发布命令`dotnet nuget push [包名称]*[忽略版本号].nupkg -k[密钥] -s [目标地址]

**Comment by dukecheng** [comment]
@cdllqos 你把windows下对DotNetLive.Framework项目的的打包批处理文件写好发这里吧.

**Comment by dukecheng** [comment]
已完成自动化打包发布: http://docs.dotnet.live/development/
