### ISSUE TITLE
方法注释说明

### ISSUE THREAD

**Issue by Leowuqunqun** [dotnetlive/dotnetlive#6]
大家Controller下面的Action方法都加上注释声明
/// 注释 切勿使用【//】
vs会根据/// 注释生成一份XML文档
我会提取xml的内容进行自动化文档生成

**Comment by dukecheng** [comment]
@Leowuqunqun 这个生成之后的文档是否可以截个图看一下
Account的API已经使用了Swagger生成dev docs [链接](http://api.account.dotnet.live/swagger/index.html)

**Comment by Leowuqunqun** [comment]
@DukeCheng 　我还没写... 我先尝试docfx的... 看看效果好不好 不好我在自己写
